#!/usr/bin/env python3
"""Initialize/upgrade the FargoVPN application PostgreSQL database.

The 3x-ui database is managed separately by 3x-ui and may use PostgreSQL.
This module owns only FargoVPN application data.
"""
from __future__ import annotations

import os
from typing import Any
import config
import db as database_adapter

# PostgreSQL DDL mirrors the production SQLite schema that was supplied for
# migration. New optional columns are added idempotently for older installs.
DDL = r"""
CREATE TABLE IF NOT EXISTS users (
    tg_id BIGINT PRIMARY KEY,
    username TEXT, display_name TEXT, uuid TEXT, email TEXT,
    expiry_time BIGINT DEFAULT 0,
    enable INTEGER DEFAULT 1,
    up BIGINT DEFAULT 0, down BIGINT DEFAULT 0, total BIGINT DEFAULT 0,
    sub_id TEXT, last_online TEXT, last_online_ts BIGINT DEFAULT 0,
    last_sync_at TEXT, last_reminder_days INTEGER DEFAULT -1,
    identity_source TEXT, identity_updated_at TEXT, notes TEXT,
    referral_code TEXT, referred_by_tg_id BIGINT, referred_by_code TEXT,
    registered_at TEXT, referral_code_updated_at BIGINT DEFAULT 0,
    registration_status TEXT DEFAULT 'awaiting_invite',
    registration_attempts INTEGER NOT NULL DEFAULT 0,
    registration_attempts_reset_at BIGINT NOT NULL DEFAULT 0,
    registration_blocked_until BIGINT NOT NULL DEFAULT 0,
    telegram_available INTEGER NOT NULL DEFAULT 1,
    telegram_unavailable_at TEXT,
    telegram_unavailable_reason TEXT
);
CREATE TABLE IF NOT EXISTS manual_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid TEXT, remark TEXT
);
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_id BIGINT NOT NULL, username TEXT, telegram_file_id TEXT,
    status TEXT DEFAULT 'pending', amount BIGINT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP, processed_at TEXT,
    processed_by TEXT, last_error TEXT,
    receipt_sha256 TEXT, receipt_text_sha256 TEXT, receipt_phash TEXT,
    receipt_amount DOUBLE PRECISION, receipt_date TEXT, receipt_phone TEXT,
    receipt_receiver TEXT, ocr_status TEXT DEFAULT 'not_checked',
    ocr_text TEXT, ocr_details TEXT, auto_approved INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    cpu DOUBLE PRECISION, ram DOUBLE PRECISION, disk DOUBLE PRECISION,
    net_in BIGINT, net_out BIGINT
);
CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP, actor TEXT, action TEXT, details TEXT
);
CREATE TABLE IF NOT EXISTS backup_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP, filename TEXT, size BIGINT,
    telegram_ok INTEGER, telegram_detail TEXT,
    google_ok INTEGER, google_detail TEXT, error TEXT
);
CREATE TABLE IF NOT EXISTS panel_notification_state (
    channel TEXT PRIMARY KEY, last_read_id BIGINT NOT NULL DEFAULT 0,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS panel_push_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT, level TEXT NOT NULL DEFAULT 'INFO',
    event TEXT NOT NULL, message TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS panel_push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    endpoint TEXT NOT NULL UNIQUE, p256dh TEXT NOT NULL, auth TEXT NOT NULL,
    user_agent TEXT, vapid_public_key TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP, last_success_at TEXT,
    last_error TEXT, enabled INTEGER NOT NULL DEFAULT 1
);
-- level_unused is only a compatibility-safe placeholder if a broken install
-- had drifted. It is harmless and never used by application code.
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_id BIGINT NOT NULL, endpoint TEXT NOT NULL UNIQUE,
    p256dh TEXT NOT NULL, auth TEXT NOT NULL, user_agent TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    last_success_at TEXT, last_error TEXT, enabled INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS web_push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL, endpoint TEXT NOT NULL UNIQUE,
    subscription_json TEXT NOT NULL, vapid_public_key TEXT, vapid_subject TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS user_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP, tg_id BIGINT NOT NULL,
    username TEXT, direction TEXT NOT NULL DEFAULT 'system',
    event_type TEXT NOT NULL DEFAULT 'event', text TEXT, actor TEXT,
    success INTEGER DEFAULT 1, metadata TEXT,
    message_kind TEXT NOT NULL DEFAULT 'message',
    delivery_status TEXT NOT NULL DEFAULT 'unknown', delivery_error TEXT,
    telegram_update_id BIGINT, telegram_chat_id BIGINT, telegram_message_id BIGINT
);
CREATE TABLE IF NOT EXISTS telegram_update_dedup (
    update_id BIGINT PRIMARY KEY,
    chat_id BIGINT, message_id BIGINT, update_type TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'processing',
    first_seen_at TEXT DEFAULT CURRENT_TIMESTAMP,
    processed_at TEXT, lease_until BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS user_message_state (
    tg_id BIGINT PRIMARY KEY,
    last_read_event_id BIGINT NOT NULL DEFAULT 0,
    last_incoming_event_id BIGINT NOT NULL DEFAULT 0,
    unread_count BIGINT NOT NULL DEFAULT 0,
    last_message_at TEXT, last_message_text TEXT
);
CREATE TABLE IF NOT EXISTS access_attempts (
    tg_id BIGINT PRIMARY KEY, attempts INTEGER NOT NULL, reset_at BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS action_rate_limits (
    identity TEXT NOT NULL, action TEXT NOT NULL,
    window_started BIGINT NOT NULL, request_count INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(identity,action)
);
CREATE TABLE IF NOT EXISTS access_invites (
    code TEXT PRIMARY KEY, owner_id BIGINT NOT NULL,
    expires_at BIGINT NOT NULL, used_by BIGINT, revoked INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS cabinet_login_requests (
    token_hash TEXT PRIMARY KEY,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at BIGINT NOT NULL, resolved_tg_id BIGINT, consumed_at TEXT
);
CREATE TABLE IF NOT EXISTS cabinet_access_tokens (
    token_hash TEXT PRIMARY KEY,
    tg_id BIGINT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at BIGINT NOT NULL,
    consumed_at TEXT
);
CREATE TABLE IF NOT EXISTS identity_import_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP, source_name TEXT,
    scanned INTEGER DEFAULT 0, matched INTEGER DEFAULT 0, updated INTEGER DEFAULT 0,
    conflicts INTEGER DEFAULT 0, panel_updated INTEGER DEFAULT 0, details TEXT
);
CREATE TABLE IF NOT EXISTS login_security (
    identity TEXT PRIMARY KEY,
    failures INTEGER NOT NULL DEFAULT 0, first_failed_at BIGINT NOT NULL DEFAULT 0,
    last_failed_at BIGINT NOT NULL DEFAULT 0, blocked_until BIGINT NOT NULL DEFAULT 0,
    blocks INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS message_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP, actor TEXT, tg_id BIGINT,
    username TEXT, message TEXT, success BOOLEAN, detail TEXT
);
CREATE TABLE IF NOT EXISTS pending_registrations (
    tg_id BIGINT PRIMARY KEY, username TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS referral_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_tg_id BIGINT NOT NULL, referred_tg_id BIGINT NOT NULL UNIQUE,
    reward_days INTEGER NOT NULL DEFAULT 10, status TEXT NOT NULL DEFAULT 'pending',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, granted_at TEXT,
    target_expiry_ms BIGINT, observed_expiry_before_ms BIGINT, details TEXT
);
CREATE TABLE IF NOT EXISTS telegram_link_requests (
    token TEXT PRIMARY KEY, local_tg_id BIGINT NOT NULL,
    created_at TEXT NOT NULL, expires_at TEXT NOT NULL, consumed_at TEXT, resolved_tg_id BIGINT
);
"""

INDEXES = r"""
CREATE INDEX IF NOT EXISTS idx_audit_log_actor_action ON audit_log(actor, action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_action_rate_limits_updated ON action_rate_limits(updated_at);
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log(created_at DESC, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_access_invites_owner_id ON access_invites(owner_id);
CREATE INDEX IF NOT EXISTS idx_backup_runs_created ON backup_runs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cabinet_login_expires ON cabinet_login_requests(expires_at);
CREATE INDEX IF NOT EXISTS idx_cabinet_access_expires ON cabinet_access_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_identity_import_created ON identity_import_runs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_security_last_failed ON login_security(last_failed_at);
CREATE INDEX IF NOT EXISTS idx_panel_notification_state_updated ON panel_notification_state(updated_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_panel_push_endpoint ON panel_push_subscriptions(endpoint);
CREATE INDEX IF NOT EXISTS idx_panel_push_enabled ON panel_push_subscriptions(enabled);
CREATE INDEX IF NOT EXISTS idx_panel_push_logs_created ON panel_push_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_panel_push_username ON panel_push_subscriptions(username);
CREATE INDEX IF NOT EXISTS idx_payments_receipt_sha ON payments(receipt_sha256);
CREATE INDEX IF NOT EXISTS idx_payments_receipt_text_sha ON payments(receipt_text_sha256);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status, id DESC);
CREATE INDEX IF NOT EXISTS idx_payments_tg_status_created ON payments(tg_id, status, id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_push_subscriptions_endpoint ON push_subscriptions(endpoint);
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_enabled ON push_subscriptions(enabled);
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_tg ON push_subscriptions(tg_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_referral_rewards_referred_tg_id ON referral_rewards(referred_tg_id);
CREATE INDEX IF NOT EXISTS idx_referral_rewards_referrer ON referral_rewards(referrer_tg_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_referral_rewards_status ON referral_rewards(status, id DESC);
CREATE INDEX IF NOT EXISTS idx_tg_link_local ON telegram_link_requests(local_tg_id);
CREATE INDEX IF NOT EXISTS idx_user_events_created ON user_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_events_incoming_id ON user_events(direction,event_type,id,tg_id);
CREATE INDEX IF NOT EXISTS idx_user_events_message_lookup ON user_events(tg_id,direction,event_type,id DESC);
CREATE INDEX IF NOT EXISTS idx_user_events_tg_id_id ON user_events(tg_id,id DESC);
CREATE INDEX IF NOT EXISTS idx_user_events_telegram_ids ON user_events(telegram_chat_id,telegram_message_id,telegram_update_id);
CREATE INDEX IF NOT EXISTS idx_user_events_direction_kind_id ON user_events(direction,message_kind,id DESC);
CREATE INDEX IF NOT EXISTS idx_user_events_tg_direction_kind_id ON user_events(tg_id,direction,message_kind,id DESC);
CREATE INDEX IF NOT EXISTS idx_telegram_update_dedup_status_lease ON telegram_update_dedup(status,lease_until);
CREATE UNIQUE INDEX IF NOT EXISTS uq_telegram_update_message ON telegram_update_dedup(chat_id,message_id,update_type) WHERE chat_id IS NOT NULL AND message_id IS NOT NULL AND update_type<>'';
CREATE INDEX IF NOT EXISTS idx_telegram_update_dedup_message ON telegram_update_dedup(chat_id,message_id,update_type);
CREATE INDEX IF NOT EXISTS idx_user_message_state_unread ON user_message_state(unread_count,last_incoming_event_id DESC);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_expiry ON users(expiry_time);
CREATE INDEX IF NOT EXISTS idx_users_last_online ON users(last_online_ts);
CREATE INDEX IF NOT EXISTS idx_users_referral_code ON users(referral_code);
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_referral_code ON users(referral_code)
WHERE referral_code IS NOT NULL AND referral_code<>'';
CREATE INDEX IF NOT EXISTS idx_users_referred_by ON users(referred_by_tg_id);
CREATE INDEX IF NOT EXISTS idx_users_registration_status ON users(registration_status, registration_blocked_until, tg_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_web_push_endpoint ON web_push_subscriptions(endpoint);
CREATE INDEX IF NOT EXISTS idx_web_push_username ON web_push_subscriptions(username);
"""

def _column_map(conn, table: str) -> dict[str,str]:
    rows = conn.execute("""
        SELECT column_name, data_type
        FROM information_schema.columns
        WHERE table_schema='public' AND table_name=?
    """,(table,)).fetchall()
    return {str(r[0]): str(r[1]) for r in rows}

def _ensure_columns(conn, table: str, columns: dict[str,str]) -> None:
    existing=_column_map(conn,table)
    for name, typ in columns.items():
        if name not in existing:
            conn.execute(f'ALTER TABLE "{table}" ADD COLUMN "{name}" {typ}')

def _migrate_registration_access(conn) -> None:
    """Add durable invitation-gate fields without demoting existing users.

    On the first upgrade from a pre-4.7.2 database, every existing Telegram
    account is treated as legacy-authorized and remains active. Rows that were
    explicitly waiting in pending_registrations are then moved to
    awaiting_invite. New rows created after the migration use the DB default
    awaiting_invite. The operation is idempotent after the first successful run.
    """
    existing = _column_map(conn, "users")
    added_status = "registration_status" not in existing
    # Keep an explicit schema marker so the manual SQL migration can be run
    # before or after the application migration without ever promoting a new
    # 4.7.2 awaiting user to active by mistake.
    conn.execute("""
        CREATE TABLE IF NOT EXISTS fargovpn_schema_migrations (
            version TEXT PRIMARY KEY,
            applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    additions = {
        "registration_status": "TEXT DEFAULT 'awaiting_invite'",
        "registration_attempts": "INTEGER NOT NULL DEFAULT 0",
        "registration_attempts_reset_at": "BIGINT NOT NULL DEFAULT 0",
        "registration_blocked_until": "BIGINT NOT NULL DEFAULT 0",
    }
    for name, typ in additions.items():
        if name not in existing:
            conn.execute(f'ALTER TABLE "users" ADD COLUMN "{name}" {typ}')

    if added_status:
        # All rows that pre-date this access-control column are legacy users.
        # Keep their access to avoid a breaking migration. Pending rows are
        # re-locked immediately below.
        conn.execute("UPDATE users SET registration_status='active' WHERE registration_status IS NULL OR registration_status='awaiting_invite'")

    conn.execute("""
        INSERT INTO fargovpn_schema_migrations(version)
        VALUES ('4.7.2-registration-access')
        ON CONFLICT(version) DO NOTHING
    """)

    # A pending_registrations row is an explicit legacy marker for a half-built
    # registration. It must win over the legacy-active migration default.
    conn.execute("""
        UPDATE users
           SET registration_status='awaiting_invite',
               registration_attempts=COALESCE(registration_attempts,0),
               registration_attempts_reset_at=COALESCE(registration_attempts_reset_at,0),
               registration_blocked_until=COALESCE(registration_blocked_until,0)
         WHERE tg_id IN (SELECT tg_id FROM pending_registrations)
           AND COALESCE(registration_status,'') <> 'banned'
    """)
    conn.execute("""
        UPDATE users
           SET registration_status='active'
         WHERE registration_status IS NULL OR TRIM(registration_status)=''
    """)
    conn.execute("""
        DELETE FROM pending_registrations
         WHERE tg_id IN (SELECT tg_id FROM users WHERE registration_status='active')
    """)

def _migrate_telegram_delivery(conn) -> None:
    """Track terminal Telegram delivery failures without affecting VPN access."""
    existing = _column_map(conn, "users")
    additions = {
        "telegram_available": "INTEGER NOT NULL DEFAULT 1",
        "telegram_unavailable_at": "TEXT",
        "telegram_unavailable_reason": "TEXT",
    }
    for name, typ in additions.items():
        if name not in existing:
            conn.execute(f'ALTER TABLE "users" ADD COLUMN "{name}" {typ}')
    conn.execute("""
        INSERT INTO fargovpn_schema_migrations(version)
        VALUES ('4.9-telegram-delivery-state')
        ON CONFLICT(version) DO NOTHING
    """)


def _normalize_message_log_success(conn) -> None:
    """Normalize old SQLite/early-PostgreSQL restores to the runtime contract."""
    column_type = _column_map(conn, "message_log").get("success", "")
    if not column_type or column_type == "boolean":
        return
    conn.execute("ALTER TABLE message_log ALTER COLUMN success DROP DEFAULT")
    conn.execute("""
        ALTER TABLE message_log
        ALTER COLUMN success TYPE BOOLEAN
        USING CASE
            WHEN success IS NULL THEN NULL
            WHEN lower(trim(CAST(success AS TEXT))) IN ('1','t','true','yes','on') THEN TRUE
            ELSE FALSE
        END
    """)


def _normalize_referral_codes(conn) -> None:
    """Clear ambiguous duplicate invitation codes before adding uniqueness."""
    conn.execute("""
        WITH ranked AS (
            SELECT tg_id, referral_code,
                   row_number() OVER (PARTITION BY referral_code ORDER BY tg_id) AS rn
              FROM users
             WHERE referral_code IS NOT NULL AND referral_code<>''
        )
        UPDATE users AS u
           SET referral_code=NULL, referral_code_updated_at=0
          FROM ranked AS r
         WHERE u.tg_id=r.tg_id AND r.rn>1
    """)

def _unread_trigger(conn) -> None:
    # Administrator IDs come from runtime configuration, never from source code.
    # This prevents a production Telegram ID from leaking into release archives.
    admin_ids = []
    for raw_id in getattr(config, "ADMIN_IDS", []) or []:
        try:
            value = int(raw_id)
        except (TypeError, ValueError):
            continue
        if value > 0:
            admin_ids.append(value)
    admin_array = ", ".join(f"{value}::bigint" for value in sorted(set(admin_ids))) or "0::bigint"
    conn.execute(f"""
    CREATE OR REPLACE FUNCTION fargovpn_user_event_unread_fn() RETURNS trigger
    LANGUAGE plpgsql AS $$
    BEGIN
      IF NEW.direction='in'
         AND NEW.event_type IN ('telegram_audio','telegram_document','telegram_message',
                                'telegram_photo','telegram_sticker','telegram_video','telegram_voice')
         AND NEW.tg_id <> ALL (ARRAY[{admin_array}]) THEN
        INSERT INTO user_message_state(
          tg_id,last_read_event_id,last_incoming_event_id,unread_count,last_message_at,last_message_text
        ) VALUES(NEW.tg_id,0,NEW.id,1,NEW.created_at,SUBSTRING(COALESCE(NEW.text,''),1,500))
        ON CONFLICT (tg_id) DO UPDATE SET
          last_incoming_event_id=GREATEST(user_message_state.last_incoming_event_id,EXCLUDED.last_incoming_event_id),
          unread_count=CASE
            WHEN EXCLUDED.last_incoming_event_id>user_message_state.last_read_event_id
            THEN GREATEST(0,user_message_state.unread_count)+1
            ELSE GREATEST(0,user_message_state.unread_count)
          END,
          last_message_at=EXCLUDED.last_message_at,
          last_message_text=SUBSTRING(COALESCE(EXCLUDED.last_message_text,''),1,500);
      END IF;
      RETURN NEW;
    END; $$;
    """)
    conn.execute("DROP TRIGGER IF EXISTS trg_user_events_unread_insert_v268 ON user_events")
    conn.execute("""
      CREATE TRIGGER trg_user_events_unread_insert_v268
      AFTER INSERT ON user_events
      FOR EACH ROW EXECUTE FUNCTION fargovpn_user_event_unread_fn()
    """)

def migrate() -> None:
    with database_adapter.connect() as conn:
        # Execute each statement independently so a prior partially-initialized
        # installation can be repaired without requiring a blank database.
        for statement in [x.strip() for x in DDL.split(";") if x.strip()]:
            conn.execute(statement)
        # add columns that appeared in later 4.x releases
        _migrate_registration_access(conn)
        _migrate_telegram_delivery(conn)
        _ensure_columns(conn,"users",{
            "identity_source":"TEXT","identity_updated_at":"TEXT","notes":"TEXT","display_name":"TEXT",
            "referral_code":"TEXT","referred_by_tg_id":"BIGINT","referred_by_code":"TEXT",
            "registered_at":"TEXT","referral_code_updated_at":"BIGINT DEFAULT 0",
        })
        _ensure_columns(conn,"payments",{
            "purchase_token":"TEXT",
            "last_error":"TEXT","receipt_sha256":"TEXT","receipt_text_sha256":"TEXT",
            "receipt_phash":"TEXT","receipt_amount":"DOUBLE PRECISION","receipt_date":"TEXT",
            "receipt_phone":"TEXT","receipt_receiver":"TEXT","ocr_status":"TEXT DEFAULT 'not_checked'",
            "ocr_text":"TEXT","ocr_details":"TEXT","auto_approved":"INTEGER DEFAULT 0",
        })
        conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_purchase_token ON payments(purchase_token) WHERE purchase_token IS NOT NULL")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_payments_user_status ON payments(tg_id,status)")
        _ensure_columns(conn,"panel_push_subscriptions",{
            "vapid_public_key":"TEXT",
        })
        _ensure_columns(conn,"cabinet_access_tokens",{
            "created_at":"TEXT DEFAULT CURRENT_TIMESTAMP",
            "consumed_at":"TEXT",
        })
        _ensure_columns(conn,"user_events",{
            "telegram_update_id":"BIGINT","telegram_chat_id":"BIGINT","telegram_message_id":"BIGINT",
            "message_kind":"TEXT DEFAULT 'message'",
            "delivery_status":"TEXT DEFAULT 'unknown'",
            "delivery_error":"TEXT",
        })
        conn.execute("""
            UPDATE user_events
               SET message_kind=CASE WHEN direction='system' THEN 'service' ELSE 'message' END
             WHERE message_kind IS NULL OR TRIM(message_kind)=''
        """)
        conn.execute("""
            UPDATE user_events
               SET delivery_status=CASE
                    WHEN direction='in' THEN 'received'
                    WHEN direction='out' AND COALESCE(success,0)<>0 THEN 'delivered'
                    WHEN direction='out' THEN 'failed'
                    ELSE 'unknown' END
             WHERE delivery_status IS NULL OR TRIM(delivery_status)='' OR delivery_status='unknown'
        """)
        _ensure_columns(conn,"backup_runs",{"google_ok":"INTEGER","google_detail":"TEXT"})
        _normalize_message_log_success(conn)
        _normalize_referral_codes(conn)
        for statement in [x.strip() for x in INDEXES.split(";") if x.strip()]:
            conn.execute(statement)
        _unread_trigger(conn)
