--
-- PostgreSQL database dump
--

\restrict CzV8VkhdFzvQQmMtlkzarztuTUOobYkWmsJpn0mwjcXXXwYBXOX3Nma7pkKnuDC

-- Dumped from database version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


--
-- Name: fargovpn_user_events_unread_insert(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.fargovpn_user_events_unread_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
                BEGIN
                    IF NEW.direction = 'in'
                       AND NEW.event_type IN (
                            'telegram_audio',
                            'telegram_document',
                            'telegram_message',
                            'telegram_photo',
                            'telegram_sticker',
                            'telegram_video',
                            'telegram_voice'
                       )
                       AND NEW.tg_id <> 53976335
                    THEN

                        INSERT INTO user_message_state (
                            tg_id,
                            last_read_event_id,
                            last_incoming_event_id,
                            unread_count,
                            last_message_at,
                            last_message_text
                        )
                        VALUES (
                            NEW.tg_id,
                            0,
                            NEW.id,
                            1,
                            NEW.created_at,
                            LEFT(COALESCE(NEW.text, ''), 500)
                        )
                        ON CONFLICT (tg_id)
                        DO UPDATE SET
                            last_incoming_event_id =
                                GREATEST(
                                    user_message_state.last_incoming_event_id,
                                    EXCLUDED.last_incoming_event_id
                                ),
                            unread_count =
                                CASE
                                    WHEN EXCLUDED.last_incoming_event_id >
                                         user_message_state.last_read_event_id
                                    THEN
                                        GREATEST(
                                            user_message_state.unread_count,
                                            0
                                        ) + 1
                                    ELSE
                                        GREATEST(
                                            user_message_state.unread_count,
                                            0
                                        )
                                END,
                            last_message_at =
                                EXCLUDED.last_message_at,
                            last_message_text =
                                EXCLUDED.last_message_text;

                    END IF;

                    RETURN NEW;
                END;
                $$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: access_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.access_attempts (
    tg_id bigint NOT NULL,
    attempts bigint NOT NULL,
    reset_at bigint NOT NULL
);


--
-- Name: access_invites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.access_invites (
    code text NOT NULL,
    owner_id bigint NOT NULL,
    expires_at bigint NOT NULL,
    used_by bigint,
    revoked bigint DEFAULT 0 NOT NULL
);


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    actor text,
    action text,
    details text
);


--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: backup_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.backup_runs (
    id bigint NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    filename text,
    size bigint,
    telegram_ok bigint,
    telegram_detail text,
    yandex_ok bigint,
    yandex_detail text,
    google_ok bigint,
    google_detail text,
    error text
);


--
-- Name: backup_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.backup_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.backup_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cabinet_login_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cabinet_login_requests (
    token_hash text NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at bigint NOT NULL,
    resolved_tg_id bigint,
    consumed_at text
);


--
-- Name: identity_import_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.identity_import_runs (
    id bigint NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    source_name text,
    scanned bigint DEFAULT 0,
    matched bigint DEFAULT 0,
    updated bigint DEFAULT 0,
    conflicts bigint DEFAULT 0,
    panel_updated bigint DEFAULT 0,
    details text
);


--
-- Name: identity_import_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.identity_import_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.identity_import_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: login_security; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.login_security (
    identity text NOT NULL,
    failures bigint DEFAULT 0 NOT NULL,
    first_failed_at bigint DEFAULT 0 NOT NULL,
    last_failed_at bigint DEFAULT 0 NOT NULL,
    blocked_until bigint DEFAULT 0 NOT NULL,
    blocks bigint DEFAULT 0 NOT NULL
);


--
-- Name: manual_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.manual_keys (
    id bigint NOT NULL,
    uuid text,
    remark text
);


--
-- Name: manual_keys_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.manual_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.manual_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message_log (
    id bigint NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    actor text,
    tg_id bigint,
    username text,
    message text,
    success bigint,
    detail text
);


--
-- Name: message_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.message_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: metrics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.metrics (
    id bigint NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    cpu double precision,
    ram double precision,
    disk double precision,
    net_in bigint,
    net_out bigint
);


--
-- Name: metrics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: panel_notification_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.panel_notification_state (
    channel text NOT NULL,
    last_read_id bigint DEFAULT 0 NOT NULL,
    updated_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: panel_push_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.panel_push_logs (
    id bigint NOT NULL,
    username text,
    level text DEFAULT 'INFO'::text NOT NULL,
    event text NOT NULL,
    message text NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: panel_push_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.panel_push_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.panel_push_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: panel_push_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.panel_push_subscriptions (
    id bigint NOT NULL,
    username text NOT NULL,
    endpoint text NOT NULL,
    p256dh text NOT NULL,
    auth text NOT NULL,
    user_agent text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text DEFAULT CURRENT_TIMESTAMP,
    last_success_at text,
    last_error text,
    enabled bigint DEFAULT 1 NOT NULL
);


--
-- Name: panel_push_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.panel_push_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.panel_push_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    tg_id bigint NOT NULL,
    username text,
    telegram_file_id text,
    status text DEFAULT 'pending'::text,
    amount bigint,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    processed_at text,
    processed_by text,
    last_error text,
    receipt_sha256 text,
    receipt_text_sha256 text,
    receipt_phash text,
    receipt_amount double precision,
    receipt_date text,
    receipt_phone text,
    receipt_receiver text,
    ocr_status text DEFAULT 'not_checked'::text,
    ocr_text text,
    ocr_details text,
    auto_approved bigint DEFAULT 0
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pending_registrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pending_registrations (
    tg_id bigint NOT NULL,
    username text,
    created_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: push_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.push_subscriptions (
    id bigint NOT NULL,
    tg_id bigint NOT NULL,
    endpoint text NOT NULL,
    p256dh text NOT NULL,
    auth text NOT NULL,
    user_agent text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text DEFAULT CURRENT_TIMESTAMP,
    last_success_at text,
    last_error text,
    enabled bigint DEFAULT 1 NOT NULL
);


--
-- Name: push_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.push_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.push_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: referral_rewards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.referral_rewards (
    id bigint NOT NULL,
    referrer_tg_id bigint NOT NULL,
    referred_tg_id bigint NOT NULL,
    reward_days bigint DEFAULT 10 NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
    granted_at text,
    target_expiry_ms bigint,
    observed_expiry_before_ms bigint,
    details text
);


--
-- Name: referral_rewards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.referral_rewards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.referral_rewards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: telegram_link_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.telegram_link_requests (
    token text NOT NULL,
    local_tg_id bigint NOT NULL,
    created_at text NOT NULL,
    expires_at text NOT NULL,
    consumed_at text,
    resolved_tg_id bigint
);


--
-- Name: user_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_events (
    id bigint NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    tg_id bigint NOT NULL,
    username text,
    direction text DEFAULT 'system'::text NOT NULL,
    event_type text DEFAULT 'event'::text NOT NULL,
    text text,
    actor text,
    success bigint DEFAULT 1,
    metadata text
);


--
-- Name: user_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_message_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_message_state (
    tg_id bigint NOT NULL,
    last_read_event_id bigint DEFAULT 0 NOT NULL,
    last_incoming_event_id bigint DEFAULT 0 NOT NULL,
    unread_count bigint DEFAULT 0 NOT NULL,
    last_message_at text,
    last_message_text text
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    tg_id bigint NOT NULL,
    username text,
    uuid text,
    email text,
    expiry_time bigint DEFAULT 0,
    enable bigint DEFAULT 0,
    up bigint DEFAULT 0,
    down bigint DEFAULT 0,
    total bigint DEFAULT 0,
    sub_id text,
    last_online text,
    last_online_ts bigint DEFAULT 0,
    last_sync_at text,
    last_reminder_days bigint DEFAULT '-1'::integer,
    identity_source text,
    identity_updated_at text,
    notes text,
    referral_code text,
    referred_by_tg_id bigint,
    referred_by_code text,
    registered_at text,
    referral_code_updated_at bigint DEFAULT 0
);


--
-- Name: web_push_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.web_push_subscriptions (
    id bigint NOT NULL,
    username text NOT NULL,
    endpoint text NOT NULL,
    subscription_json text NOT NULL,
    vapid_public_key text,
    vapid_subject text,
    created_at text DEFAULT CURRENT_TIMESTAMP,
    updated_at text DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: web_push_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.web_push_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.web_push_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: access_attempts access_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_attempts
    ADD CONSTRAINT access_attempts_pkey PRIMARY KEY (tg_id);


--
-- Name: access_invites access_invites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_invites
    ADD CONSTRAINT access_invites_pkey PRIMARY KEY (code);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: backup_runs backup_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backup_runs
    ADD CONSTRAINT backup_runs_pkey PRIMARY KEY (id);


--
-- Name: cabinet_login_requests cabinet_login_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cabinet_login_requests
    ADD CONSTRAINT cabinet_login_requests_pkey PRIMARY KEY (token_hash);


--
-- Name: identity_import_runs identity_import_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.identity_import_runs
    ADD CONSTRAINT identity_import_runs_pkey PRIMARY KEY (id);


--
-- Name: login_security login_security_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.login_security
    ADD CONSTRAINT login_security_pkey PRIMARY KEY (identity);


--
-- Name: manual_keys manual_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manual_keys
    ADD CONSTRAINT manual_keys_pkey PRIMARY KEY (id);


--
-- Name: message_log message_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_log
    ADD CONSTRAINT message_log_pkey PRIMARY KEY (id);


--
-- Name: metrics metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.metrics
    ADD CONSTRAINT metrics_pkey PRIMARY KEY (id);


--
-- Name: panel_notification_state panel_notification_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.panel_notification_state
    ADD CONSTRAINT panel_notification_state_pkey PRIMARY KEY (channel);


--
-- Name: panel_push_logs panel_push_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.panel_push_logs
    ADD CONSTRAINT panel_push_logs_pkey PRIMARY KEY (id);


--
-- Name: panel_push_subscriptions panel_push_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.panel_push_subscriptions
    ADD CONSTRAINT panel_push_subscriptions_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: pending_registrations pending_registrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_registrations
    ADD CONSTRAINT pending_registrations_pkey PRIMARY KEY (tg_id);


--
-- Name: push_subscriptions push_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.push_subscriptions
    ADD CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id);


--
-- Name: referral_rewards referral_rewards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_rewards
    ADD CONSTRAINT referral_rewards_pkey PRIMARY KEY (id);


--
-- Name: telegram_link_requests telegram_link_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telegram_link_requests
    ADD CONSTRAINT telegram_link_requests_pkey PRIMARY KEY (token);


--
-- Name: user_events user_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_events
    ADD CONSTRAINT user_events_pkey PRIMARY KEY (id);


--
-- Name: user_message_state user_message_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_message_state
    ADD CONSTRAINT user_message_state_pkey PRIMARY KEY (tg_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (tg_id);


--
-- Name: web_push_subscriptions web_push_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.web_push_subscriptions
    ADD CONSTRAINT web_push_subscriptions_pkey PRIMARY KEY (id);


--
-- Name: idx_audit_log_actor_action; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_log_actor_action ON public.audit_log USING btree (actor, action, created_at DESC);


--
-- Name: idx_audit_log_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_log_created ON public.audit_log USING btree (created_at DESC, id DESC);


--
-- Name: idx_backup_runs_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_backup_runs_created ON public.backup_runs USING btree (created_at DESC);


--
-- Name: idx_cabinet_login_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cabinet_login_expires ON public.cabinet_login_requests USING btree (expires_at);


--
-- Name: idx_identity_import_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_identity_import_created ON public.identity_import_runs USING btree (created_at DESC);


--
-- Name: idx_login_security_last_failed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_login_security_last_failed ON public.login_security USING btree (last_failed_at);


--
-- Name: idx_panel_notification_state_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_panel_notification_state_updated ON public.panel_notification_state USING btree (updated_at);


--
-- Name: idx_panel_push_enabled; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_panel_push_enabled ON public.panel_push_subscriptions USING btree (enabled);


--
-- Name: idx_panel_push_logs_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_panel_push_logs_created ON public.panel_push_logs USING btree (created_at DESC);


--
-- Name: idx_panel_push_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_panel_push_username ON public.panel_push_subscriptions USING btree (username);


--
-- Name: idx_payments_receipt_sha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payments_receipt_sha ON public.payments USING btree (receipt_sha256);


--
-- Name: idx_payments_receipt_text_sha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payments_receipt_text_sha ON public.payments USING btree (receipt_text_sha256);


--
-- Name: idx_payments_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payments_status ON public.payments USING btree (status, id DESC);


--
-- Name: idx_push_subscriptions_enabled; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_push_subscriptions_enabled ON public.push_subscriptions USING btree (enabled);


--
-- Name: idx_push_subscriptions_tg; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_push_subscriptions_tg ON public.push_subscriptions USING btree (tg_id);


--
-- Name: idx_referral_rewards_referrer; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_referral_rewards_referrer ON public.referral_rewards USING btree (referrer_tg_id, id DESC);


--
-- Name: idx_referral_rewards_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_referral_rewards_status ON public.referral_rewards USING btree (status, id DESC);


--
-- Name: idx_tg_link_local; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tg_link_local ON public.telegram_link_requests USING btree (local_tg_id);


--
-- Name: idx_user_events_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_events_created ON public.user_events USING btree (created_at DESC);


--
-- Name: idx_user_events_incoming_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_events_incoming_id ON public.user_events USING btree (direction, event_type, id, tg_id);


--
-- Name: idx_user_events_message_lookup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_events_message_lookup ON public.user_events USING btree (tg_id, direction, event_type, id DESC);


--
-- Name: idx_user_events_tg_id_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_events_tg_id_id ON public.user_events USING btree (tg_id, id DESC);


--
-- Name: idx_user_message_state_unread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_message_state_unread ON public.user_message_state USING btree (unread_count, last_incoming_event_id DESC);


--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_email ON public.users USING btree (email);


--
-- Name: idx_users_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_expiry ON public.users USING btree (expiry_time);


--
-- Name: idx_users_last_online; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_last_online ON public.users USING btree (last_online_ts);


--
-- Name: idx_users_referral_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_referral_code ON public.users USING btree (referral_code);


--
-- Name: idx_users_referred_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_referred_by ON public.users USING btree (referred_by_tg_id);


--
-- Name: idx_web_push_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_web_push_username ON public.web_push_subscriptions USING btree (username);


--
-- Name: sqlite_autoindex_access_invites_2; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX sqlite_autoindex_access_invites_2 ON public.access_invites USING btree (owner_id);


--
-- Name: sqlite_autoindex_panel_push_subscriptions_1; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX sqlite_autoindex_panel_push_subscriptions_1 ON public.panel_push_subscriptions USING btree (endpoint);


--
-- Name: sqlite_autoindex_push_subscriptions_1; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX sqlite_autoindex_push_subscriptions_1 ON public.push_subscriptions USING btree (endpoint);


--
-- Name: sqlite_autoindex_referral_rewards_1; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX sqlite_autoindex_referral_rewards_1 ON public.referral_rewards USING btree (referred_tg_id);


--
-- Name: sqlite_autoindex_web_push_subscriptions_1; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX sqlite_autoindex_web_push_subscriptions_1 ON public.web_push_subscriptions USING btree (endpoint);


--
-- Name: user_events trg_user_events_unread_insert_v268; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_user_events_unread_insert_v268 AFTER INSERT ON public.user_events FOR EACH ROW EXECUTE FUNCTION public.fargovpn_user_events_unread_insert();


--
-- PostgreSQL database dump complete
--

\unrestrict CzV8VkhdFzvQQmMtlkzarztuTUOobYkWmsJpn0mwjcXXXwYBXOX3Nma7pkKnuDC

