const fs=require('fs'),{JSDOM,VirtualConsole,ResourceLoader}=require(process.env.FARGOVPN_JSDOM_PATH);
class Loader extends ResourceLoader{fetch(url){let p=new URL(url).pathname;if(p.includes('/static/'))return Promise.resolve(fs.readFileSync(process.argv[2]+'/static/'+p.split('/static/')[1]));return null;}}
async function test(name){const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('Could not parse CSS'))errors.push(e.name)});
const dom=new JSDOM(fs.readFileSync(process.argv[3]+'/'+name+'.html','utf8'),{url:'https://offline.invalid/qa-panel/'+name+'?tab=notifications',resources:new Loader(),runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.scrollTo=()=>{};w.Request=Request;w.Headers=Headers;w.AbortController=AbortController;w.AbortSignal=AbortSignal;w.TextEncoder=TextEncoder;w.confirm=()=>false;w.fetch=async()=>({ok:true,status:200,json:async()=>({ok:true,logs:[],lines:[],items:[],state:'idle',progress:0}),headers:new Headers({'content-type':'application/json'})});}});
await new Promise(r=>setTimeout(r,300));const w=dom.window,d=w.document;let combinations=0;
if(name==='users'){const rows=[...d.querySelectorAll('.user-row')],q=d.getElementById('user-filter-search'),st=d.querySelector('[data-filter-status]'),so=d.querySelector('[data-filter-sort]'),order=d.querySelector('[data-filter-order]');const seed=rows.find(x=>x.dataset.userName)?.dataset.userName||'x';for(let query of ['',seed,seed.slice(0,3),'__definitely_not_a_user__'])for(let status of ['all','active','expired','blocked','online'])for(let sort of ['remaining','last_online','traffic','quota','name','registration'])for(let direction of ['asc','desc']){q.value=query;st.value=status;so.value=sort;order.value=direction;st.dispatchEvent(new w.Event('change'));const expected=rows.filter(x=>(!query||x.dataset.userSearch.toLocaleLowerCase('ru-RU').includes(query.toLocaleLowerCase('ru-RU')))&&(status==='all'||status==='online'&&x.dataset.userOnline==='1'||x.dataset.userStatus===status));const visible=[...d.querySelectorAll('.user-row')].filter(x=>!x.hidden);if(Number(d.getElementById('users-visible-count').textContent)!==expected.length||visible.length!==Math.min(50,expected.length))throw Error('real dataset filter mismatch');combinations++;}st.value='all';q.value='';st.dispatchEvent(new w.Event('change'));if(Number(d.getElementById('users-visible-count').textContent)!==rows.length)throw Error('users disappeared');}
if(errors.length)throw Error(name+': JS runtime errors '+errors.length);
console.log(JSON.stringify({page:name,result:'passed',combinations}));dom.window.close();}
(async()=>{for(const name of ['users','messages','payments','audit','reminders','settings'])await test(name);})().catch(e=>{console.error(e.name);process.exitCode=1;});
