const fs=require('fs'),{JSDOM}=require(process.env.FARGOVPN_JSDOM_PATH||'jsdom');
const source=fs.readFileSync(process.argv[2]+'/webapp.py','utf8');const start=source.indexOf("const f=document.querySelector('[data-user-filter-form]');"),end=source.indexOf('})();</script>',start);
const code=source.slice(start,end);const count=5000;
const controls='<div data-user-filter-form><input id="user-filter-search"><select data-filter-status><option>all</option><option>active</option><option>expired</option><option>blocked</option><option>online</option></select><select data-filter-sort><option>remaining</option><option>traffic</option><option>name</option></select><select data-filter-order><option>asc</option><option>desc</option></select></div><div data-user-pagination data-initial-page="1"><button data-page-prev></button><span data-page-label></span><button data-page-next></button></div><span id="users-visible-count"></span><span id="users-total-count"></span>';
let rows='';for(let i=0;i<count;i++)rows+=`<div class="user-row" data-user-tg-id="${i}" data-user-search="user${i}" data-user-name="user${i}" data-user-status="${i%2?'active':'expired'}" data-user-online="${i%3===0?'1':'0'}" data-user-remaining="${i}" data-user-traffic="${count-i}"></div>`;
const started=Date.now();const dom=new JSDOM(controls+'<div class="user-list">'+rows+'</div>',{url:'https://test/qa-panel/users',runScripts:'outside-only'});const w=dom.window,d=w.document;
w.eval('(function(){const setText=(e,v)=>e.textContent=v;'+code+'})();');
for(let i=0;i<20;i++){const status=d.querySelector('[data-filter-status]');status.value=i%2?'active':'all';status.dispatchEvent(new w.Event('change'));if(Number(d.getElementById('users-visible-count').textContent)!==(i%2?2500:5000))throw Error('stress filter');if(d.querySelectorAll('.user-row:not([hidden])').length!==50)throw Error('stress pagination');}
const q=d.getElementById('user-filter-search');q.value='no-match';d.querySelector('[data-filter-status]').dispatchEvent(new w.Event('change'));if(!d.querySelector('.user-list').textContent.includes('Пользователи не найдены'))throw Error('empty missing');
console.log(JSON.stringify({users:count,changes:20,ms:Date.now()-started,heapMiB:Math.round(require('v8').getHeapStatistics().used_heap_size/1024/1024)}));dom.window.close();
